### ISSUE TITLE
【Q010】将footer固定在页面底部的实现方法

### ISSUE THREAD

**Issue by fly0o0** [silver-hands/css-questions#10]
```html
<body>
    <header>header</header>
    <main>main content</main>
    <footer>footer</footer>
</body>
```

```css
html {
  height: 100%;
}

body {
  min-height: 100%;
  margin: 0;
  padding: 0;
  position: relative;
}

header {
  background-color: red;
}

main {
  padding-bottom: 100px;
  background-color: yellow;
}

/* main的padding-bottom值要等于或大于footer的height值 */
footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 100px;
  background-color: blue;
}
```
> https://codepen.io/chuge/pen/abvPwEV
